
server:
  port: 9999

spring:
  application:
    name: zuul-service

eureka:
   client:
      serviceUrl:
        defaultZone: http://localhost:8888/eureka/

management:
  security:
    enabled: false
