server:
  port: 8012

spring:
  application:
    name: APIConfigServer
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/MyProject/practice-java/udemy-spring-cloud/APIConfigServer/src/main/resources/native
        git:
          uri: https://github.com/thongchaiSH/DemoAppConfiguration
          username: thongchaiSH
          password: a0487682596
          clone-on-start: true
          default-label: main

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh,bean,health,routes,httptrace



