server:
  port: 8012

spring:
  application:
    name: APIConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thongchaiSH/DemoAppConfiguration
          username: thongchaiSH
          password: ba344a0ed65cf90071fc0b185c38c88b4a63a0e5
          clone-on-start: true
          default-label: main


