server:
  port: ${PORT:0}
spring:
  application:
    name: users-ws
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    # password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registryFetchIntervalSeconds: 5
  instance:
    instance-id: ${spring.application.name}:${random.value}